$( document ).ready(function() {
$("#one").hide();
$("#two").hide();
$("#three").hide();
$("#four").hide();
$("#five").hide();
$("#six").hide();
$("#stage1").hide();
$("#stage2").hide();
$("#seven").hide();
$("#eight").hide();
$("#nine").hide();
$("#ten").hide();
$("#eleven").hide();
$("#twelve").hide();
$("#stage3").hide();
$("#thirteen").hide();
$("#fourteen").hide();
$("#fifteen").hide();
$("#sixteen").hide();
 $("#seventeen").hide();
$("#eighteen").hide();
$("#nineteen").hide();
$("#twenty").hide();
$("#twentyone").hide();
$("#twentytwo").hide();
$("#twentythree").hide();
$("#twentyfour").hide();
$("#twentyfive").hide();
$("#twentysix").hide();
$("#twentyseven").hide();
$("#twentyeight").hide();
$("#twentynine").hide();
$("#thirty").hide();
$("#bomb").hide();
$("#bomb2").hide();
$("#bomb3").hide();
$("#bomb4").hide();
$("#bomb5").hide();
$("#bomb6").hide();
$("#bomb7").hide();
$("#bomb8").hide();
$("#bomb9").hide();
$("#bomb10").hide();
$("#bomb11").hide();
$("#bomb12").hide();
$("#bomb13").hide();
$("#bomb14").hide();
$("#bomb15").hide();
$("#bomb16").hide();
$("#bomb17").hide();
$("#bomb18").hide();
$("#bomb19").hide();
$("#bomb20").hide();
$("#bomb21").hide();
$("#bomb22").hide();
$("#bomb23").hide();
$("#bomb24").hide();
$("#stagefour").hide();
$("#laststage").hide();
$("#end").hide();
$("#pagerefresh").hide();
$("#word").hide();
$("#wordtwo").hide();
$("#wordthree").hide();
$("#wordfour").hide();
$("#wordfive").hide();
$("#wordsix").hide();
$("#wordseven").hide();
$("#wordeight").hide();
$("#di").hide();
$("#picture").hide();
$("#continuetwo").hide();
$("#continue").hide();
$("#continuethree").hide();
$("#continuefour").hide();
$("#skip").hide();
$("#gameover").hide();
$("#gameover1").hide();
$("#gameover2").hide();
$("#gameover3").hide();
$("#gameover4").hide();
$("#gameover5").hide();
$("#gameover6").hide();
$("#gameover7").hide();
$("#gameover8").hide();
$("#gameover9").hide();
$("#gameover10").hide();
$("#gameover11").hide();
$("#gameover12").hide();
$("#gameover13").hide();
$("#gameover14").hide();
$("#gameover15").hide();
$("#gameover16").hide();
$("#gameover17").hide();
$("#gameover18").hide();
$("#gameover19").hide();
$("#gameover20").hide();
$("#gameover20").hide();
$("#gameover21").hide();
$("#gameover22").hide();
$("#gameover23").hide();
$("#gameover24").hide();
$("#gameover25").hide();
$("#gameover26").hide();
$("#gameover27").hide();
$("#gameover28").hide();
$("#boxes").hide();
$("#begin").hide();


$("#skip").click(function(){
$("#word").hide();
$("#picture").hide();
$("#di").hide();
$("#wordtwo").hide();
$("#wordthree").hide();
$("#wordfour").hide();
$("#wordfive").hide();
$("#wordsix").hide();
$("#wordseven").hide();
$("#start").delay(1000).fadeIn();
$("#instruction").delay(2000).fadeIn();
$("#continue").hide();
$("#continuetwo").hide();
$("#continuethree").hide();
$("#continuefour").hide();
$("#skip").hide();
});

$("#begin").click(function(){
	$("#begin").hide();
	$("#di").delay(2000).fadeIn();
	$("#picture").delay(1000).fadeIn();
	$("#continue").delay(5000).fadeIn();
	$("#word").delay(3000).fadeIn();
	$("#wordtwo").delay(4000).fadeIn();
  $("#skip").delay(5000).fadeIn();
})
$("#continue").click(function(){
$("#word").hide();
$("#wordtwo").hide();
$("#wordthree").delay(1000).fadeIn();
$("#wordfour").delay(2000).fadeIn();
$("#continue").hide();
$("#continuetwo").delay(3000).fadeIn();
});

$("#continuetwo").click(function(){
$("#wordthree").hide();
$("#wordfour").hide();
$("#wordfive").delay(1000).fadeIn();
$("#wordsix").delay(2000).fadeIn();
$("#continuetwo").hide();
$("#continuethree").delay(3000).fadeIn();
});

$("#continuethree").click(function(){
$("#wordfive").hide();
$("#wordsix").hide();
$("#wordseven").delay(1000).fadeIn();
$("#wordeight").delay(2000).fadeIn();
$("#continuethree").hide();
$("#continuefour").delay(3000).fadeIn();
});

$("#continuefour").click(function(){
$("#continuefour").hide();
$("#picture").hide();
$("#di").hide();
$("#wordseven").hide();
$("#wordeight").hide();
$("#start").delay(1000).fadeIn();
$("#instruction").delay(2000).fadeIn();
$("#skip").hide();
});

$("#start").click(function(){
  $("#start").hide();
  $("#one").show();
  $("#one").fadeOut(2500);
  $("#stage1").show();
  $("#stage1").fadeOut(2500);
  $("#instruction").hide();
  $("#title").hide();
  $("#title2").hide();
});
$("#one").click(function(){
  $("#three").show();
   $("#three").fadeOut(2500);
  $("#one").hide();
  $("#pagerefresh").delay(5000).fadeIn();
  $("#gameover1").delay(5000).fadeIn();
});
$("#three").click(function(){
  $("#gameover1").hide();
  $("#two").show();
    $("#two").fadeOut(2500);
    $("#three").hide();
    $("#pagerefresh").delay(5000).fadeIn();
    $("#gameover2").delay(5000).fadeIn();
});
$("#two").click(function(){
  $("#gameover2").hide();
  $("#four").show();
  $("#four").fadeOut(2500);
  $("#two").hide();
  $("#pagerefresh").delay(5000).fadeIn();
  $("#gameover3").delay(5000).fadeIn();
});
$("#four").click(function(){
    $("#gameover4").hide();
  $("#five").show();
    $("#five").fadeOut(2500);
  $("#four").hide();
  $("#pagerefresh").delay(5000).fadeIn();
  $("#gameover3").delay(5000).fadeIn();
});
$("#five").click(function(){
  $("#gameover4").hide();
  $("#six").show();
   $("#six").fadeOut(2500);
   $("#five").hide();
  $("#pagerefresh").delay(5000).fadeIn();
    $("#gameover5").delay(5000).fadeIn();
});
$("#six").click(function(){
  $("#gameover5").hide();
  $("#stage2").show();
  $("#stage2").fadeOut(2500);
  $("#seven").show();
  $("#seven").fadeOut(2000);
  $("#six").hide();
  $("#pagerefresh").delay(5000).fadeIn();
  $("#gameover6").delay(5000).fadeIn();
});
$("#seven").click(function(){
  $("#gameover6").hide();
  $("#seven").hide();
  $("#eight").show();
  $("#eight").fadeOut(2000);
  $("#pagerefresh").delay(5000).fadeIn();
  $("#gameover7").delay(5000).fadeIn();
});
$("#eight").click(function(){
     $("#gameover7").hide();
  $("#eight").hide();
  $("#nine").show();
  $("#nine").fadeOut(2000);
  $("#pagerefresh").delay(5000).fadeIn();
  $("#gameover8").delay(5000).fadeIn();
});
$("#nine").click(function(){
    $("#gameover8").hide();
  $("#nine").hide();
  $("#ten").show();
  $("#ten").fadeOut(2000);
  $("#pagerefresh").delay(5000).fadeIn();
  $("#gameover9").delay(5000).fadeIn();
});
$("#ten").click(function(){
$("#gameover9").hide();
$("#ten").hide();  
$("#eleven").show();
$("#eleven").fadeOut(2000);
$("#pagerefresh").delay(5000).fadeIn();
$("#gameover10").delay(5000).fadeIn();
});
$("#eleven").click(function(){
    $("#gameover10").hide();
  $("#eleven").hide();
  $("#twelve").show();
  $("#twelve").fadeOut(2000);
  $("#pagerefresh").delay(5000).fadeIn();
  $("#gameover11").delay(5000).fadeIn();
});
$("#twelve").click(function(){
    $("#gameover11").hide();
  $("#twelve").hide();
  $("#stage3").show();
  $("#stage3").fadeOut(2500);
  $("#bomb").show();
  $("#bomb").fadeOut(2000);
  $("#thirteen").show();
  $("#thirteen").fadeOut(1000);
  $("#pagerefresh").delay(5000).fadeIn();
  $("#gameover12").delay(5000).fadeIn();
});

$("#thirteen").click(function(){
    $("#gameover12").hide();
$("#thirteen").hide();
$("#bomb2").show();
$("#bomb2").fadeOut(1000);
$("#fourteen").show();
$("#fourteen").fadeOut(1500);
$("#pagerefresh").delay(5000).fadeIn();
$("#gameover13").delay(5000).fadeIn();
 });

$("#pagerefresh").click(function(){
$("#pagerefresh").hide();
$("#start").delay(3000).fadeIn();
$("#instruction").delay(4000).fadeIn();
$("#title").delay(1000).fadeIn();
$("#title2").delay(2000).fadeIn();
$("#gameover1").hide();
$("#gameover2").hide();
$("#gameover3").hide();
$("#gameover4").hide();
$("#gameover5").hide();
$("#gameover6").hide();
$("#gameover7").hide();
$("#gameover8").hide();
$("#gameover9").hide();
$("#gameover10").hide();
$("#gameover11").hide();
$("#gameover12").hide();
$("#gameover13").hide();
$("#gameover14").hide();
$("#gameover15").hide();
$("#gameover16").hide();
$("#gameover17").hide();
$("#gameover18").hide();
$("#gameover19").hide();
$("#gameover20").hide();
$("#gameover21").hide();
$("#gameover22").hide();
$("#gameover23").hide();
$("#gameover24").hide();
$("#gameover25").hide();
$("#gameover26").hide();
$("#gameover27").hide();
$("#gameover28").hide();
});

$("#fourteen").click(function(){
    $("#gameover13").hide();
$("#fourteen").hide();
$("#bomb3").show();
$("#bomb3").fadeOut(1000);
$("#fifteen").show();
$("#fifteen").fadeOut(1500);
$("#pagerefresh").delay(5000).fadeIn();
$("#gameover14").delay(5000).fadeIn();
 });


$("#fifteen").click(function(){
    $("#gameover14").hide();
$("#fifteen").hide();
$("#bomb4").show();
$("#bomb4").fadeOut(1000);
$("#sixteen").show();
$("#sixteen").fadeOut(1500);
$("#pagerefresh").delay(5000).fadeIn();
$("#gameover15").delay(5000).fadeIn();
 });

$("#sixteen").click(function(){
    $("#gameover15").hide();
$("#sixteen").hide();
$("#bomb5").show();
$("#bomb5").fadeOut(1000);
$("#seventeen").show();
$("#seventeen").fadeOut(1500);
$("#pagerefresh").delay(5000).fadeIn();
$("#gameover16").delay(5000).fadeIn();
 });

$("#seventeen").click(function(){
    $("#gameover16").hide();
$("#seventeen").hide();
$("#bomb6").show();
$("#bomb6").fadeOut(500);
$("#eighteen").show();
$("#eighteen").fadeOut(500);
$("#stagefour").show();
$("#stagefour").fadeOut(2500);
$("#pagerefresh").delay(5000).fadeIn();
$("#gameover17").delay(5000).fadeIn();
 });

$("#eighteen").click(function(){
    $("#gameover17").hide();
$("#eighteen").hide();
$("#bomb7").show();
$("#bomb7").fadeOut(500);
$("#nineteen").show();
$("#nineteen").fadeOut(1000);
$("#pagerefresh").delay(5000).fadeIn();
$("#gameover18").delay(5000).fadeIn();
 });

$("#nineteen").click(function(){
    $("#gameover18").hide();
$("#nineteen").hide();
$("#bomb8").show();
$("#bomb8").fadeOut(500);
$("#twenty").show();
$("#twenty").fadeOut(1000);
$("#pagerefresh").delay(5000).fadeIn();
$("#gameover19").delay(5000).fadeIn();
 });

$("#twenty").click(function(){
    $("#gameover19").hide();
$("#twenty").hide();
$("#bomb9").show();
$("#bomb9").fadeOut(500);
$("#twentyone").show();
$("#twentyone").fadeOut(1000);
$("#pagerefresh").delay(5000).fadeIn();
$("#gameover20").delay(5000).fadeIn();
 });

$("#twentyone").click(function(){
    $("#gameover20").hide();
$("#twentyone").hide();
$("#bomb10").show();
$("#bomb10").fadeOut(500);
$("#twentytwo").show();
$("#twentytwo").fadeOut(1000);
$("#pagerefresh").delay(5000).fadeIn();
$("#gameover21").delay(5000).fadeIn();
 });

$("#twentytwo").click(function(){
    $("#gameover21").hide();
$("#twentytwo").hide();
$("#bomb11").show();
$("#bomb11").fadeOut(500);
$("#twentythree").show();
$("#twentythree").fadeOut(1000);
$("#pagerefresh").delay(5000).fadeIn();
$("#gameover22").delay(5000).fadeIn();
 });

$("#twentythree").click(function(){
    $("#gameover22").hide();
$("#twentythree").hide();
$("#bomb12").show();
$("#bomb12").fadeOut(300);
$("#bomb13").show();
$("#bomb13").fadeOut(300);
$("#laststage").show();
$("#laststage").fadeOut(1500);
$("#twentyfour").show();
$("#twentyfour").fadeOut(500);
$("#pagerefresh").delay(5000).fadeIn();
$("#gameover23").delay(5000).fadeIn();
 });

$("#twentyfour").click(function(){
    $("#gameover23").hide();
$("#twentyfour").hide();
$("#bomb14").show();
$("#bomb14").fadeOut(300);
$("#bomb15").show();
$("#bomb15").fadeOut(300);
$("#twentyfive").show();
$("#twentyfive").fadeOut(500);
$("#pagerefresh").delay(5000).fadeIn();
$("#gameover24").delay(5000).fadeIn();
 });

$("#twentyfive").click(function(){
    $("#gameover24").hide();
$("#twentyfive").hide();
$("#bomb16").show();
$("#bomb16").fadeOut(300);
$("#bomb17").show();
$("#bomb17").fadeOut(300);
$("#twentysix").show();
$("#twentysix").fadeOut(500);
$("#pagerefresh").delay(5000).fadeIn();
$("#gameover25").delay(5000).fadeIn();
 });

$("#twentysix").click(function(){
    $("#gameover25").hide();
$("#twentysix").hide();
$("#bomb18").show();
$("#bomb18").fadeOut(300);
$("#bomb19").show();
$("#bomb19").fadeOut(300);
$("#twentyseven").show();
$("#twentyseven").fadeOut(500);
$("#pagerefresh").delay(5000).fadeIn();
$("#gameover26").delay(5000).fadeIn();
 });

$("#twentyseven").click(function(){
    $("#gameover26").hide();
$("#twentyseven").hide();
$("#bomb24").show();
$("#bomb24").fadeOut(300);
$("#twentyeight").show();
$("#twentyeight").fadeOut(400);
$("#pagerefresh").delay(5000).fadeIn();
$("#gameover27").delay(5000).fadeIn();
 });

$("#twentyeight").click(function(){
    $("#gameover27").hide();
$("#twentyeight").hide();
$("#end").show();
$("#pagerefresh").delay(5000).fadeIn();
$("#gameover28").delay(5000).fadeIn();
 });

$("#bomb").click(function(){
  $("#gameover").show();
});
$("#bomb1").click(function(){
  $("#gameover").show();
});
$("#bomb2").click(function(){
  $("#gameover").show();
});
$("#bomb3").click(function(){
  $("#gameover").show();
});
$("#bomb4").click(function(){
  $("#gameover").show();
});
$("#bomb5").click(function(){
  $("#gameover").show();
});
$("#bomb6").click(function(){
  $("#gameover").show();
});
$("#bomb7").click(function(){
  $("#gameover").show();
});
$("#bomb8").click(function(){
  $("#gameover").show();
});
$("#bomb9").click(function(){
  $("#gameover").show();
});
$("#bomb10").click(function(){
  $("#gameover").show();
});
$("#bomb11").click(function(){
  $("#gameover").show();
});
$("#bomb12").click(function(){
  $("#gameover").show();
});
$("#bomb13").click(function(){
  $("#gameover").show();
});
$("#bomb14").click(function(){
  $("#gameover").show();
});
$("#bomb15").click(function(){
  $("#gameover").show();
});
$("#bomb16").click(function(){
  $("#gameover").show();
});
$("#bomb17").click(function(){
  $("#gameover").show();
});
$("#bomb18").click(function(){
  $("#gameover").show();
});
$("#bomb19").click(function(){
  $("#gameover").show();
});
$("#bomb20").click(function(){
  $("#gameover").show();
});
$("#bomb21").click(function(){
  $("#gameover").show();
});
$("#bomb22").click(function(){
  $("#gameover").show();
});
$("#bomb23").click(function(){
  $("#gameover").show();
});
$("#bomb24").click(function(){
  $("#gameover").show();
});

});